<?php 
// @see Omx_Hooks_Block_Omxpricing_Checkout_Cart_Freeitem
?>
<?php 
// Only display the discount total if the currentConnectionState is TRUE to avoid 
//inconsistent displays if connection gets lost DURING checkout.
if ($this->canSelect() && $this->getCurrentConnectionState() ):?>
<?php $freeItemSelections = $this->getFreeItemSelections('unselected');?>
<?php if(count($freeItemSelections) ): ?>
<div class="omxdiscount">
	<h2><?php echo Mage::helper('hooks/data')->__('Add a Free Item');?></h2>
	<form action="<?php echo $this->getUrl('hooks/omxpricing/item') ?>add" method="post" id="omxfreeitem-form">
    <fieldset>
	<ul>
    <?php foreach($freeItemSelections as $selection) : ?>
    	<li>
    		<?php if (count($selection['items']) > 1) :?>
            <label for="omxdiscount:<?php echo $selection['policyId'].'_'.$selection['lineReference'] ?>" ><?php echo Mage::helper('hooks/data')->__($selection['name']);?></label>
    		<select name="omxdiscount[<?php echo $selection['policyId'].'_'.$selection['lineReference']?>]" id="omxdiscount:<?php echo $selection['policyId'].'_'.$selection['lineReference'] ?>" class="omx-free-item-choice">
    	    	<option />
    		    <?php foreach ($selection['items'] as $key=>$item) : ?>
    			<option id="omxdiscount:<?php echo $selection['policyId'].'_'.$selection['lineReference'] ?>" value="<?php echo $item['itemCode']?>" >(<?php echo $item['qty']?> x) <?php echo $item['name']?></option>    
    		    <?php endforeach; ?>
    	    </select>
    	    <?php elseif(count($selection['items']) == 1) :?>
    	    	<label for="omxdiscount:<?php echo $selection['policyId'].'_'.$selection['lineReference'] ?>" ><?php echo Mage::helper('hooks/data')->__($selection['name']);?></label>
    	    	<input type="checkbox" name="omxdiscount[<?php echo $selection['policyId'].'_'.$selection['lineReference']?>]" id="omxdiscount:<?php echo $selection['items'][0]['itemCode']?>" value="<?php echo $selection['items'][0]['itemCode']?>"/>
    	    	<span>(<?php echo $selection['items'][0]['qty']?> x) <?php echo  $selection['items'][0]['name']?></span>
    	    <?php endif; ?>
        </li>
    <?php endforeach; // ($freeItemSelections as $selection) ?>
    </ul>
    </fieldset>
        <button type="button" class="button" onclick="omxfreeitemForm.submit()">
        	<span>
        		<span>
        		    <?php echo $this->__('Add Free Item') ?>
        		</span>
        	</span>
        </button>
</form>
</div>
<script type="text/javascript">
//<![CDATA[
	var omxfreeitemForm = new VarienForm('omxfreeitem-form');
//]]>
</script>
<?php endif; // END: (count($freeItemSelections) ?>
<?php endif; // END: ($this->canSelect()) ?>