<?php
//@see Omx_Hooks_Block_Omxpricing_Checkout_Onepage_Omxdiscount
// This is the template for the onpage checkout step
?>
<?php 
    $unselectedPolicies = $this->getFreeItemSelections('unselected');
    $selectedPolicies = $this->getFreeItemSelections('selected');
?>
	<?php if(!$this->isUpdate()) :?>
	<div id="checkout-omxdiscount-load">
	<?php endif;?>
	<form action="" id="co-omxdiscount-form">
        <?php if (count($unselectedPolicies)) :?>
        <fieldset>
            <h3><?php echo $this->__('Add a Free Item:')?></h3>
        	<ul>
            <?php foreach($unselectedPolicies as $selection) : ?>
            	<li>
            		<?php if (count($selection['items']) > 1) :?>
            		<div class="omx-policy-name">
                        <label for="omxdiscount:<?php echo $selection['policyId'].'_'.$selection['lineReference'] ?>" ><?php echo $this->__($selection['name']);?></label>
            		</div>
            		<select name="omxdiscount[<?php echo $selection['policyId'].'_'.$selection['lineReference']?>]" id="omxdiscount:<?php echo $selection['policyId'].'_'.$selection['lineReference'] ?>" class="omx-free-item-choice">
            	    	<option />
            		    <?php foreach ($selection['items'] as $key=>$item) : ?>
            			<option id="omxdiscount:<?php echo $selection['policyId'].'_'.$selection['lineReference'] ?>" value="<?php echo $item['itemCode']?>" >(<?php echo $item['qty']?> x) <?php echo $item['name']?></option>    
            		    <?php endforeach; ?>
            	    </select>
            	    <?php elseif(count($selection['items']) == 1) :?>
            	    <div class="omx-policy-name">
                	   	<label for="omxdiscount:<?php echo $selection['policyId'].'_'.$selection['lineReference'] ?>" ><?php echo $this->__($selection['name']);?></label>
            	    </div>
            	    <input type="checkbox" name="omxdiscount[<?php echo $selection['policyId'].'_'.$selection['lineReference']?>]" id="omxdiscount:<?php echo $selection['items'][0]['itemCode']?>" value="<?php echo $selection['items'][0]['itemCode']?>"/>
            	    <span>(<?php echo $selection['items'][0]['qty']?> x) <?php echo  $selection['items'][0]['name']?></span>
            	    <?php endif; ?>
                </li>
            <?php endforeach; // ($unselectedPolicies as $selection) ?>
            </ul>
        </fieldset>
        <?php endif;?>
        <?php if(count($selectedPolicies)) :?>
        <fieldset>
            <h3><?php echo $this->__('Free Items on your Cart:')?></h3>
        	<ul>
            <?php foreach($selectedPolicies as $selection) : ?>
            	<li>
            		<div class="omx-policy-name">
                		<label for="omxdiscount:<?php echo $selection['policyId'].'_'.$selection['lineReference'] ?>" ><?php echo $this->__($selection['name']);?></label>
            	    </div>
            		<?php if (count($selection['items']) > 1) :?>
            		  	<?php foreach ($selection['items'] as $key=>$item) : ?>
            		  	<?php if ($item['itemCode'] == $selection['selectedItem']) :?>
            			<input type="checkbox" name="omxdiscount[<?php echo $selection['policyId'].'_'.$selection['lineReference']?>]" id="omxdiscount:<?php echo $selection['policyId'].'_'.$selection['lineReference'] ?>" value="<?php echo $item['itemCode']?>" checked="checked" disabled="disabled"/>
            			<span>(<?php echo $selection['items'][$key]['qty']?> x) <?php echo  $selection['items'][$key]['name']?></span>  
            		    <?php endif;?>
            		  	<?php endforeach; ?>
            	     <?php elseif(count($selection['items']) == 1) :?>
            	    	<input type="checkbox" name="omxdiscount[<?php echo $selection['policyId'].'_'.$selection['lineReference']?>]" id="omxdiscount:<?php echo $selection['items'][0]['itemCode']?>" value="<?php echo $selection['items'][0]['itemCode']?>"checked="checked" disabled="disabled"/>
            	    	<span>(<?php echo $selection['items'][0]['qty']?> x) <?php echo  $selection['items'][0]['name']?></span>
            	    <?php endif; ?>
                </li>
            <?php endforeach; // ($unselectedPolicies as $selection) ?>
            </ul>
        </fieldset>
        <?php endif;?>
    	
    	
        
        <div class="buttons-set form-buttons" id="omxdiscount-buttons-container">
            <p class="back-link">
            	<a href="#" onclick="checkout.back(); return false;">
            		<small>&laquo; </small>
            		    <?php echo $this->__('Back') ?>
            	</a>
           	</p>
            <button type="button" class="button" onclick="omxdiscount.save()">
            	<span>
            		<span>
            		    <?php echo $this->__('Continue') ?>
            		</span>
            	</span>
            </button>
            <span id="omxdiscount-please-wait" class="please-wait" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Loading next step...') ?></span>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
            var omxdiscount = new Omxdiscount('co-omxdiscount-form', '<?php echo $this->getUrl('checkout/onepage/saveOmxdiscount') ?>');
         	var omxdiscountForm = new VarienForm('co-omxdiscount-form');
    //]]>
    </script>
<?php if(!$this->isUpdate()) :?>
</div> <!-- id="checkout-omxdiscount-load" -->
<?php endif;?>

