<?php
/**
 * This template is a wrapper. Depending on the settingd the related block-class will 
 * fill it with either the original Magento gift card block 
 * (Enterprise_GiftCardAccount_Block_Checkout_Cart_Giftcardaccount) or the Omx gift certifacte block
 * 
 * @see Omx_Hooks_Block_Checkout_Cart_Giftcardaccount
 */
?>
<div class="giftcardwrapper">
<?php echo $this->giftCertBlock->toHtml(); ?>
</div>
