<?php
/**
 * @see Omx_Hooks_Block_Giftcertificate_Cart 
 */

?>

<div class="giftcard omxgiftcertificate">
	<h2><?php echo $this->__('Gift Certificate') ?></h2>
    <div id="giftcertificate_balance_lookup"></div>
    <span id="gc-please-wait" class="please-wait" style="display:none;">
        <img 
        	src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" 
        	alt="" class="v-middle" 
        /> 
        <?php echo $this->__('Please wait, loading...') ?>
    </span>
    <form id="omxgiftcertificate-form" action="<?php echo $this->getUrl('hooks/giftcertificate/add') ?>" method="post">
        <fieldset>
            <label for="giftcertificate_code"><?php echo $this->__('Enter the gift certificate code') ?></label>
            <div class="v-fix">
            	<input class="required-entry input-text" id="giftcertificate_code" name="giftcertificate_code" value="" />
            </div>
            <button 
            	class="button" 
            	onclick="omxgiftcertificateForm.submit()" 
            	type="button" 
            	value="<?php echo $this->__('Add Gift Certificate') ?>">
            	<span>
            		<span>
            		    <?php echo $this->__('Add Gift Certificate') ?>
            		</span>
            	</span>
            </button>
            <button
            	class="button check-gc-status"
            	onclick="new Ajax.Updater(
            		'giftcertificate_balance_lookup', 
            		'<?php echo Mage::getUrl('hooks/giftcertificate/check') ?>', 
            	    {
            	    	onCreate: function() { $('gc-please-wait').show() }, 
            	    	onComplete: function() { $('gc-please-wait').hide() }, 
            	    	parameters : {giftcertificate_code : $('giftcertificate_code').value}
            	    }
            	   )" 
            	type="button" 
            	value="<?php echo $this->__('Check Gift Certificate status and balance') ?>">
            		<span>
            			<span>
            		        <?php echo $this->__('Check Gift Certificate status and balance') ?>
            		    </span>
            		</span>
            </button>
        </fieldset>
    </form>
	<!-- This is for form validation (using standard Prototype function) -->
    <script type="text/javascript">
    //<![CDATA[
    var omxgiftcertificateForm = new VarienForm('omxgiftcertificate-form');
    //]]>
    </script>    
</div>